### ISSUE TITLE
不要放弃生活

### ISSUE THREAD

**Issue by CrackerCat** [4ra1n/FINAL#1]
我的文笔不是很好，下面的内容可能带着一点说教，但是希望你能好好活着，不要轻易的放弃生命，只要人活着，就一切都有可能，加油。

看你写的内容，你应该是被某一个所谓的“大佬”pua了，然后自己陷入了死胡同，不过我相信你后面能走出来的，不要放弃，更不要因为那些伤害你的人而放弃，要活得更好。

 
![image](https://user-images.githubusercontent.com/17995064/179868754-4ced2f6a-e34b-419b-b0e0-ce1a9cea5374.png)
你这里提到那个所谓的“大佬”多次嘲讽你，我认为就是在PUA你，你也不用太在意，毕竟他可能都不如你。

![image](https://user-images.githubusercontent.com/17995064/179869064-0cd0f11e-da11-4f36-b860-c9ee3f08064f.png)

不要在意那些所谓的安全圈，很多就是娱乐圈。我以前认为的某大佬，接触过以后才发现人品和技术都不行，靠自己的名气割韭菜罢了。

![image](https://user-images.githubusercontent.com/17995064/179869202-c93a2365-8fbb-41d7-beca-de206d66dad2.png)

找不到实习工作不代表你的能力不行，可能是岗位不适合或者没有hc，至于“托关系询问得知：HC充足，拒绝我仅因为我垃圾，太菜。”，你有没有想过是面试官太菜，所以你说的东西他无法理解。

![image](https://user-images.githubusercontent.com/17995064/179869485-95f55e5d-7c63-41fe-bad5-8bef3d78b626.png)
个人认为找工作就像找对象，有时候就是看缘分，所以不要太纠结，要相信自己，不要在一颗树上吊死。很多hr有面试指标的，他们有可能就是把你当作刷面试的指标罢了，实际根本不招人。

![image](https://user-images.githubusercontent.com/17995064/179869898-ce8fd916-46be-451f-bebd-9ac19c4accc3.png)
千万不要放弃，人生还有很多选择，你这就是钻牛角尖了，多经历一些就好了。

![image](https://user-images.githubusercontent.com/17995064/179870043-59c68afa-41e3-4473-a497-317878e7da92.png)
在我看来，这就是大佬，包括我在内，可能很多搞安全人一辈子都做不到。很多小白可能就是看着你的文章才开始进入安全这个行业。

![image](https://user-images.githubusercontent.com/17995064/179870438-cf1e08e6-fef0-43f6-8396-9b9a7fe83152.png)
千万不要再钻牛角尖了，为自己而活，不要在乎其他人的看法。

![image](https://user-images.githubusercontent.com/17995064/179870558-c1392111-9629-4fd4-ac43-9505f607861a.png)
其实我也想过，如果失业了去跑dd,送外卖，然后把安全当作自己的兴趣爱好，但是千万不要想不开。无论如何，都要活着，如果能活得比那个所谓的“大佬”活得更好，那就更好了；如果不行，那至少要比他活得长，等他死了去挖他的祖坟。

**Comment by 4ra1n** [comment]
感谢关心
